version: "3.9"
services:
  service:
    build: .
    ports:
      - "5000:5000"

  db:
    build: db/
    ports:
      - "5432:5432"

  web:
    build: web/clerk-data-web/
    ports:
      - "5555:5555"